name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install system packages for native extensions and Xvfb
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev build-essential xvfb python3-tk
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-mock httpx pytest-asyncio pandas
    - name: Test with pytest (headless)
      run: |
        xvfb-run -a pytest tests/
